name: Test Recce Cloud

permissions:
  contents: read

on:
  push:
    branches:
      - main
    paths:
      - "recce_cloud/**"
  pull_request:
    branches:
      - main
    paths:
      - "recce_cloud/**"

jobs:
  test:
    name: Test Recce Cloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Install recce-cloud package and run tests
        working-directory: recce_cloud
        run: |
          uv venv
          uv pip install -e .[dev]
          uv run flake8 ../recce_cloud/
          uv run pytest tests/
